name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight
  workflow_dispatch:      # allows manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: 'Sulemanaddu'        # 👈 your GitHub username
          outputs: dist/github-snake.svg dist/github-snake-dark.svg

      - name: Commit & push SVGs to output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions[bot]'
          author_email: '41898282+github-actions[bot]@users.noreply.github.com'
          message: 'chore(snake): update generated snake svgs'
          add: 'dist/**'
          branch: 'output'
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
